### ISSUE TITLE
Criar tela de cadastro de usuário

### ISSUE THREAD

**Issue by jonatan2m** [UnicariocaDev/projetofinal#10]
Essa tela deve conter os seguintes campos:
- Nome, Email e Senha.

Por padrão, não existe o campo Nome no modelo do asp.net identity, ou seja, será preciso adicionar essa propriedade no modelo.
O modelo é a classe ApplicationUser e a propriedade deve ficar dentro dessa classe.
Também é necessário habilitar as migrações.

**Comment by Zeds2015** [comment]
já tem uma classe com esse nome
Será necessário criar outra?

**Comment by jonatan2m** [comment]
"...Será preciso adicionar essas propriedades ao modelo..."
Nenhuma classe deve ser criada.

**Comment by Zeds2015** [comment]
beleza eu pensei o mesmo
já está quase pronto :3

**Comment by jonatan2m** [comment]
Essa tarefa já está pronta?
