### ISSUE TITLE
colocar um botao de adicionar a playlist também na popup de detalhes

### ISSUE THREAD

**Issue by jonatan2m** [UnicariocaDev/projetofinal#13]
Exatamente como descrito na issue para adicionar o botão na grid

**Comment by Zeds2015** [comment]
Jonatan, acho que sem querer eu fiz essa também

só falta tirar o script, da página HTML.

**Comment by jonatan2m** [comment]
Sem problemas. Só se certificar que está tudo Ok e pode fechar.

**Comment by jonatan2m** [comment]
Precisamos fechar essa task. Está pronta?
@Zeds2015 @lpbastardo @tukpedro @NataliaMiranda
