### ISSUE TITLE
na popup de detalhes, colocar um campo para avaliar o filme (5 estrelas)

### ISSUE THREAD

**Issue by jonatan2m** [UnicariocaDev/projetofinal#14]

**Comment by jonatan2m** [comment]
Como está o andamento desta tarefa?

**Comment by tukpedro** [comment]
Realizei alguns testes e deixei o resultado no trello!

**Comment by Thamiresvs** [comment]
Estou fazendo, mas nenhum sucesso até agora. Conseguir guardar a avaliação, mas não como estrela. Continuo pesquisando e mexendo, porém sem sucesso

**Comment by Zeds2015** [comment]
já tentaram olhar esse site

http://stackoverflow.com/questions/1987524/turn-a-number-into-star-rating-display-using-jquery-and-css

**Comment by Zeds2015** [comment]
amanhã que tal uma call?
