### ISSUE TITLE
Criar link "Minhas PlayLists" na tela principal quando o usuario estiver logado

### ISSUE THREAD

**Issue by tukpedro** [UnicariocaDev/projetofinal#20]
Atualmente para se entrar na playlist criada, deve-se entrar no "criar playlist"

**Comment by Zeds2015** [comment]
eu também tinha pensado nisso, boa Pastuk

**Comment by Zeds2015** [comment]
mas temos de pensar no front um pouco, pois coloquei no criar playlist, justamente para não ter muitos botões na tela, ficaria 4 no meu monitor padrão de notebook, não ficaria legal eu pensei, por isso coloquei lá, bom vou acertar isso e tirar um print antes de comentar ai você também tira suas conclusões.

**Comment by Zeds2015** [comment]
vou mandar no seu skype...
