### ISSUE TITLE
Criar Playlist Ver Depois

### ISSUE THREAD

**Issue by NataliaMiranda** [UnicariocaDev/projetofinal#21]
## **Analista** de Testes responsável pelos parecer: Natália Miranda **(@NataliaMiranda)**

Supervisão:  **Hugo Silva**  **(@HugoBex)**
## **Teste** [1]

**2-(CT-01)**  **Criar playlist na forma padrão**
Está ok
**3**-**[ERRO]** O filme selecionado pelo usuário não está sendo adicionado na playlist, a mesma continua vazia.

**3.1-** **Dados de Entrada:**
1- Botão buscar filmes
2 - Campo buscar nome do filme
3- Nome do filme a ser buscado: matrix
4- Botão adicionar na playlist
5- Clicar no botão Home
6- Clicar no botão Criar Playlist
7- Clicar no link Ver suas Playlists
8- Clicar em Detalhes

**3.2- Como simular o erro?**
Ir na playlist criada e verificar que não tem filme lá dentro 

**3.3 - Resultado esperado:**
Filme adicionado na playlist

**3.4 Resultado Obtido:**
Filme não está na playlist
## **Teste[2]**

**2-(CT-02)** **Assistir Depois**

**3- [ERRO]** A playlist ver depois existe, entretanto o filme selecionado pelo usuário para assistir depois não é encaminhado a playlist, ou seja, a mesma continua vazia (ou é adicionado, mas não aparece)

**3.1- Dados de Entrada**
1- Botão buscar filmes
2 - Campo buscar nome do filme
3- Nome do filme a ser buscado: matrix
4- Selecionar 'Ver Depois'
5- Clicar no botão Home
6- Clicar no botão Criar Playlist
7- Clicar no link Ver suas Playlists
8- Clicar em Detalhes

**3.2 - Como simular o erro?**
Ir até a playlist 'Ver Depois' e verificar que não tem nenhum filme contido nela.

**3.3 - Resultado esperado:**
Filme adicionado a playlist ver depois

**3.4 - Resultado obtido:**
Filme não está na playlist 'Ver Depois'

**Comment by Zeds2015** [comment]
O teste 1, teve o mesmo resultado do teste 2. Lembrando que a playlist ver depois é compartilhada ou seja se implementar esta funcionalidade você conseguirá ver os filmes de todos os outros usuários, adicionados lá dentro.  p. ex eu adicionei Eurotrip, Jonatan adicionou Matrix, qualquer outro usuario pode ir lá e ver o filme que nós adicionamos. Pois a chave é compartilhada entre muitos outros usuários. 

E os filmes estão sim sendo adicionados a playlist, é só ver pelo banco de dados, apenas não implementamos a funcionalidade de observar os filmes que estão lá. Ao meu ver isso não é um bug, apenas uma task importante.  Desculpa o meu jeito de falar.

**Comment by Zeds2015** [comment]
E sinceramente pelo pouco que pude observar existe outra tag de bug, com o mesmo problema aqui.

**Comment by NataliaMiranda** [comment]
Uma mensagem é enviada ao usuário de que o filme foi adicionado, mas, quando você abre a playlist não tem nenhum filme ali dentro. Não estou afirmando que não está sendo adicionado, tanto que ali no caso de teste coloquei entre parênteses a seguinte frase '' (ou é adicionado, mas não aparece)". Que seja um bug ou task importante, estamos trabalhando juntos para que o projeto funcione da maneira correta ou da melhor forma possível.

**Comment by Zeds2015** [comment]
Ah sim, eu pensei que disse que não estava adicionando. E sim ele não mostra apenas adiciona, concordo com sua opinião.

eu não vi essa frase. Desculpa, e sim estamos juntos para fazer o melhor possível [😊]

---

De: NataliaMiranda notifications@github.com
Enviado: quinta-feira, 15 de setembro de 2016 16:38:28
Para: UnicariocaDev/projetofinal
Cc: Mateus Arruda; Assign
Assunto: Re: [UnicariocaDev/projetofinal] Criar Playlist Ver Depois (#21)

Uma mensagem é enviada ao usuário de que o filme foi adicionado, mas, quando você abre a playlist não tem nenhum filme ali dentro. Não estou afirmando que não está sendo adicionado, tanto que ali no caso de teste coloquei entre parênteses a seguinte frase '' (ou é adicionado, mas não aparece)". Que seja um bug ou task importante, estamos trabalhando juntos para que o projeto funcione da maneira correta ou da melhor forma possível.

**Comment by jonatan2m** [comment]
Essa funcionalidade nao esta implementada ainda.
O conceito de Bug eh para funcionalidades que ja foram criadas, funcionavam e pararam de funcionar por algum motivo.
Alinhei essa questao com o Hugo agora e estou fechando esse bug.
