### ISSUE TITLE
[Teste](CSU-12) Manter PlayList [tarefas 11-12]

### ISSUE THREAD

**Issue by tukpedro** [UnicariocaDev/projetofinal#22]
# Analista de Testes responsável pelos parecer: Pedro Pastuk (@tukpedro)

Supervisão: Hugo Silva (@HugoBex)

Teste [1]

2 - (CT-01) Fluxo Padrão

3 -[Erro] Filme nao aparece adicionado na playlist

3.1 -Resultado Esperado
- Filme adicionado e visivel na playlist

3.2 - Resultado Obtido
- Filme não é adicionado ou visivel na playlist

3.3 - Como simular o erro:
- Buscar um filme
- Clicar no botao "+"
- Aparece a mensagem "Filme adicionado a playlist"
- Quando se abre a playlist, o filme nao aparece

4- Teste Interrompido

**Comment by Zeds2015** [comment]
Tem certeza que está com erro?

**Comment by jonatan2m** [comment]
Lembrando que se tiver testando no ambiente de homologação, o código está desatualizado.
@tukpedro @Zeds2015

**Comment by Zeds2015** [comment]
acabei de baixar o código do Git, e está funcionalidade aqui está funcionando, quando clico no botão. Ele adiciona ao banco de dados.

**Comment by Zeds2015** [comment]
creio que não seja um bug, apenas falta implementar a opção visualizar filmes em uma determinada playlist.
