### ISSUE TITLE
Mensagem retornada para o usuário na criação da playlist

### ISSUE THREAD

**Issue by NataliaMiranda** [UnicariocaDev/projetofinal#30]
No momento da criação de uma nova playlist, o usuário da um nome para a playlist e é obrigatório que a opção publica ou privado seja marcada. Caso o usuário não selecione nenhuma das opções e tente criar a playlist, a mensagem "The Publica field is required" é retornada para ele. É importante que a mensagem seja alterada para português afim de que não haja erro de consistência

**Comment by Zeds2015** [comment]
Vou commitar
