### ISSUE TITLE
Erro de formatação do pop up "Detalhes"

### ISSUE THREAD

**Issue by tukpedro** [UnicariocaDev/projetofinal#31]
Ao abrir detalhes do filme, quando se passa o mouse pelo botao add, nao aparece as playlists criadas. 

![captura de tela 2016-09-17 12 18 24](https://cloud.githubusercontent.com/assets/19653613/18609131/dd547f28-7cd0-11e6-900e-ff3ab66af21d.png)

**Comment by Zeds2015** [comment]
As playlists aparecem, porém o navegador pode vir a dar uma certa interferencia, e você tem que apertar o botão pra descer a tela, assim podendo ter uma visualização melhor.
