### ISSUE TITLE
Erro ao buscar um filme com título inválido

### ISSUE THREAD

**Issue by tukpedro** [UnicariocaDev/projetofinal#33]
Ao buscar um filme escrevendo um conjunto de caracteres aleatórios, não acontece nada. 

Deveria ter um aviso "Filme não existe".

![captura de tela 2016-09-17 12 52 53](https://cloud.githubusercontent.com/assets/19653613/18609339/09e870f8-7cd6-11e6-876c-2b450938bcaa.png)

**Comment by Zeds2015** [comment]
Por que fui tirar o link de lá, meu deus rsrs.
