### ISSUE TITLE
dado inválido no campo nome ao cadastrar usuário

### ISSUE THREAD

**Issue by NataliaMiranda** [UnicariocaDev/projetofinal#35]
Ao cadastrar um novo usuário, o campo nome deve ser preenchido apenas com letras. O sistema está permitindo que seja cadastrado letras e números.

**Comment by Zeds2015** [comment]
Na verdade o Philipe já tinha visto e até resolvido isso, mas quando reparei a linha tinha sido apagada, provavelmente deva ter sido um descuido meu, desculpa.

**Comment by NataliaMiranda** [comment]
tranquilo Matheus :)
