### ISSUE TITLE
Erro ao buscar um filme com título inválido 2

### ISSUE THREAD

**Issue by tukpedro** [UnicariocaDev/projetofinal#36]
Ao buscar um titulo de filme invalido, a imagem de erro não carrega.

![captura de tela 2016-09-19 13 59 45](https://cloud.githubusercontent.com/assets/19653613/18641130/9b0e7c34-7e71-11e6-992c-d2f7679136f5.png)
![captura de tela 2016-09-19 13 59 55](https://cloud.githubusercontent.com/assets/19653613/18641132/9b10784a-7e71-11e6-909c-41827b2acb05.png)
![captura de tela 2016-09-19 14 00 02](https://cloud.githubusercontent.com/assets/19653613/18641129/9b0c6318-7e71-11e6-8e47-3c683f673ced.png)

**Comment by sockadm** [comment]
Resolvido
