### ISSUE TITLE
Formatação da lista de  PlayLists

### ISSUE THREAD

**Issue by tukpedro** [UnicariocaDev/projetofinal#37]
Quando se entra na lista de playlists criadas, aparece a segunda e terceira coluna "Publica" e "Padrao". Não se pode alterar nem mexer em nada, tornando desnecessário manter visível para o usuário.

![captura de tela 2016-09-19 14 18 00](https://cloud.githubusercontent.com/assets/19653613/18642030/768f11ee-7e75-11e6-899e-e291fc635cc9.png)

**Comment by Zeds2015** [comment]
Tem certeza que isso é bug???

**Comment by Zeds2015** [comment]
Adorei essa sugestão

**Comment by Zeds2015** [comment]
Mas não é bug, em minha opinião
