### ISSUE TITLE
Aparece opçao de add filme que ja está adicionado a playlist

### ISSUE THREAD

**Issue by tukpedro** [UnicariocaDev/projetofinal#38]
Poderia ter um aviso de quais playlists ele está add (??)

![captura de tela 2016-09-19 14 37 31](https://cloud.githubusercontent.com/assets/19653613/18642403/df2bf68a-7e76-11e6-80eb-fa1bc9d42447.png)

**Comment by Zeds2015** [comment]
de novo tem certeza que isso é bug?

**Comment by tukpedro** [comment]
pode nao ser um bug, mas pra que aparece a opção se o filme já está add?

**Comment by Zeds2015** [comment]
meio que permite ao usuário adicionar o mesmo filme a outras playlists... ai vai do usuário de adicionar ou não o filme, em outra playlist

**Comment by sockadm** [comment]
Entendo que isto não é um bug, pois o usuário pode adiocionar o mesmo filme em outra playlist. 
Bug seria adicionar o mesmo filme duas vezes na mesma playlist...

**Comment by Zeds2015** [comment]
Está task está aberta?, e tem alguem ainda mexendo no projeto?
