### ISSUE TITLE
Sistema permite PlayList com nomes iguais

### ISSUE THREAD

**Issue by tukpedro** [UnicariocaDev/projetofinal#39]
![captura de tela 2016-09-19 14 41 57](https://cloud.githubusercontent.com/assets/19653613/18642499/3f8d936c-7e77-11e6-8bb2-b89cf8ffc94a.png)

**Comment by Zeds2015** [comment]
tem certeza que isso é um bug?

**Comment by sockadm** [comment]
Resolvido. 
Falta fazer ajuste para de aviso ao usuário com o padrão do site

**Comment by Zeds2015** [comment]
tipo colocar aquele toastr?
