### ISSUE TITLE
Criar Serviço para consumir a API do RT, retornando os dados buscados.

### ISSUE THREAD

**Issue by jonatan2m** [UnicariocaDev/projetofinal#4]
chamada HTTP, GET, JSON.
criar uma classe que encapsula tudo isso e utilizar HttpClient

**Comment by Zeds2015** [comment]
Criei um try catch caso o servidor não responda

**Comment by Zeds2015** [comment]
servidor não, o site com a API.

**Comment by Zeds2015** [comment]
servidor não, o site com a API.

**Comment by raphacm** [comment]
alteração dos parâmetros de busca, feitos. Agora retorna uma lista de filmes!
