### ISSUE TITLE
Dropdown nao funciona

### ISSUE THREAD

**Issue by tukpedro** [UnicariocaDev/projetofinal#40]
Quando se tenta add filme pelo botao do pop detalhes, o dropdown nao funciona direito e nao se consegue add o filme.

![captura de tela 2016-09-19 14 46 33](https://cloud.githubusercontent.com/assets/19653613/18642708/1cb9cd00-7e78-11e6-9842-ba4babf9ac2a.png)

**Comment by Thamiresvs** [comment]
Já foi modificado a cor e o tamanho

**Comment by Zeds2015** [comment]
Creio que o Jonatan tenha resolvido isso.
