### ISSUE TITLE
Criar função para excluir playlist

### ISSUE THREAD

**Issue by sockadm** [UnicariocaDev/projetofinal#42]
Adicionar Método para excluir uma playlist criada

**Comment by Zeds2015** [comment]
Sinceramente acho boa a funcionalidade, mas prefiro a ideia do usuario não poder excluir a playlist, apenas um filme que esteja nela

**Comment by sockadm** [comment]
Esta funcionalidade é para exclusão apenas de listas criadas por ele mesmo.
