### ISSUE TITLE
Cor das estrelas de avaliação

### ISSUE THREAD

**Issue by tukpedro** [UnicariocaDev/projetofinal#46]
Quando se passa o mouse por cima das estrelas, elas ficam amarelas. Mas depois que se avalia, elas ficam verdes e sublinhadas. Não poderia ficar amarela?

![captura de tela 2016-09-20 13 12 40](https://cloud.githubusercontent.com/assets/19653613/18678905/f47a1f72-7f33-11e6-9922-cd7400efbbd7.png)
![captura de tela 2016-09-20 13 12 43](https://cloud.githubusercontent.com/assets/19653613/18678906/f495db22-7f33-11e6-8041-5cf75dcaa382.png)

**Comment by Thamiresvs** [comment]
Já foi modificado a cor e o tamanho

**Comment by tukpedro** [comment]
Ainda continua!

![captura de tela 2016-09-21 19 52 57 2](https://cloud.githubusercontent.com/assets/19653613/18731845/174a9340-8035-11e6-96d7-b29562f1ae4d.png)
![Uploading Captura de tela 2016-09-21 19.52.57.png…]()

**Comment by Zeds2015** [comment]
Jonatan já fechou essa
