### ISSUE TITLE
sistema permite que o mesmo filme seja adicionado mais de uma vez na playlist Ver Depois

### ISSUE THREAD

**Issue by NataliaMiranda** [UnicariocaDev/projetofinal#49]
O usuário digita o nome do filme no campo de buscar e ao adicionar o filme na playlist ver depois, o sistema permite que seja adicionado várias vezes o mesmo filme

**Comment by Zeds2015** [comment]
Na verdade essa playlist é geral no sistema, e o controle é feito por usuário, o que aparece nos detalhes da mesma playlist são os filmes dos próprios usuários. Seria como impedir do usuario alocar na playlist dele tal filme, só porque outro usuário tem o mesmo alocado.

**Comment by Zeds2015** [comment]
Seria como impedir do usuário alocar o filme, só porque existe outro usuário com o mesmo filme locado.

**Comment by Zeds2015** [comment]
1- Conecte-se com um usuário;
2- Acrescente um filme a playlist do usuário atual;
3- Vá em detalhes da playlist;
4- Veja o filme alocado;
5- Saia da conta do usuário;
6- Entre, ou cadastre uma nova conta;
7- Adicione o mesmo filme na playlist;
8- E após isso vá em detalhes;
9- Verá que nenhum filme está ali;
10- Adicione o mesmo filme a playlist;
11- Pronto ele estará lá.

Isso é por causa do controle, ele é de usuário, e não global.
